name:		'Ankerite'
formula:	'Ca(Mg, Fe2+, Mn)(CO3)2'
colour: 	'White/Yellowish white'
abundance: 	'Frequently fills joints in coal seams'
hardness: 	'3.5 - 4 (Soft - Medium)'
lustre: 	'Vitreous to pearly'
ore: 		'Gangue mineral accompanying iron ore'
fact: 		'Darkens with heating and may become magnetic'
uses: 		'Minor iron ore'
extractors: 'N/A'
chabit: 	'Rhombohedral with curved faces, columnar, granular, massive'
cstruct: 	'Trigonal'
depenv:		'Result of both hydrothermal, low-temperature metasomatism and banded iron formations'
tparency: 	'Translucent - transparent'
origin: 	'Named after M. J. Anker, an Austrian mineralogist'
observed: 	'Cream, brown'
usesplus: 	'None'
streak: 	'White'
cleavage: 	'Perfect'
fracture: 	'Subconchoidal'
gravity: 	'2.93 - 3.10'
properties: 'Colour turns yellowish brown/brown when oxidation of iron has occured'
relevance: 	'Large concentration of ankerite accompany galena-sphalerite-fluorite-baryte veins such as in the North Pennines orefield where limestone or quartz dolerite has been replaced'
opprop: 	'Increasing replacement of Mg by Fe2+ increases the refractive indices, birefringence and specific gravity'
other:      ''
hero:		'ankerite.jpeg'
thumb:		'ankerite-thumb.jpeg'