name:		'Aragonite'
formula:	'CaCO3'
colour: 	'It can be white, colourless, grey, yellowish, reddish and green'
abundance: 	'Extremely common on the seafloor as it forms in almost all mollusk shells, and as the calcareous endoskeleton of warm and cold water corals'
hardness: 	'3 - 3.5 (soft to medium)'
lustre: 	'Vitreous inclining to resinous'
ore: 		'None'
fact: 		'Aragonite is considered essential for the replication of reef conditions in aquariums. It is the material that sea life is evolved to use and live around and also keeps the tank's pH close to its natural level'
uses: 		'Aquariums, gemstones'
extractors: 'Facet-quality crystals come from the Czech Republic, superb cave growths from Mexico and flos-ferri from Austria and Greece'
chabit: 	'Prismatic, acicular, columnar or fibrous. Occasionally in branching stalactitic forms called “flos-ferri” meaning “flowers of iron” due to their association with ores at Carinthian iron mines'
cstruct: 	'Orthorhombic'
depenv:		'Sedimentary formations and evaporite deposits, hot spring deposits, hydrothermal ore veins, igneous traprock environments, and metamorphic schists'
tparency: 	'Transparent to translucent'
origin:		'The type location for aragonite is Molina de Aragón (Guadalajara, Spain), 25 km from Aragon for which it was named in 1797'
observed: 	'White'
usesplus: 	'Layered aragonite is sometimes polished and sold as \'onyx\''
streak: 	'White'
cleavage: 	'Distinct'
fracture: 	'Subconchoidal'
gravity: 	'4.3'
properties: 'None'
relevance: 	'Often found with iron ores and used in spar boxes'
opprop: 	'Biaxial'
impurities:	'Various impurities lead to the vast selection of colours described'
hero:		'aragonite.jpeg'
thumb:		'aragonite-thumb.jpeg'