name:		'Baryte'
formula:	'BaS04'
colour: 	'White, often tinged with yellow, brown, blue, green or red'
abundance: 	'Found worldwide'
hardness: 	'2 - 3 (brittle)'
lustre: 	'Vitreous'
ore: 		'None'
fact: 		'It will glow green, blue or yellow under ultraviolet light'
uses: 		'A component of heavy cement, it is crushed and screened to a uniform size'
extractors: 'China, India, USA, Morocco, Turkey and Kazakhstan'
chabit: 	'Tabular, with a prismatic habit giving the diamond-shaped outline with fibrous, coxcomb, granular and stalagmitic habits also being associated with this mineral'
cstruct: 	'Orthorhombic'
depenv:		'It is deposited during evaporation and biogenic processes and as a vein filling gangue mineral, as well as being identified in meteorites'
tparency: 	'Transparent to translucent.'
origin:		'Derived from the Greek word βαρύς meaning heavy'
observed: 	'White, brown and yellow'
usesplus: 	'Varies the weight of well drilling mud in the production of petroleum which helps eliminate large differences in pressure between it, and the hydrocarbons, preventing kicks and subsequent catastrophic blow outs such as the incident in the Gulf of Mexico'
streak: 	'White'
cleavage: 	'Well observed, displaying perfect basal, and very good prismatic cleavage'
fracture: 	'Uneven'
gravity: 	'4.3 - 4.6'
properties: 'In the deep oceans, baryte crystallises out and forms a significant amount of sediments. With oxygen forming part of the crystal structure, we can use it to gather paleotemperatures to a maximum of 25 Ma in conjunction with the  δ18O values. Similar variations of sulphur are also being exploited'
relevance: 	'Deposition is associated with galena'
opprop: 	'Biaxial positive'
impurities:	'Yellow, red and brown caused by iron oxides, hydroxides, sulphides and organic matter whilst blue colours indicate exposure of radiation'
hero:		'baryte.jpeg'
thumb:		'baryte-thumb.jpeg'