name:		'Calcite'
formula:	'CaCO3'
colour: 	'Usually colourless or white but shades of grey, yellow, green, red, purple, blue and even brown or black'
abundance: 	'It is found in virtually every country as a major constituent in calcareous sedimentary rocks such as limestone and its metamorphic equivalent (marble)'
hardness: 	'3 (medium to soft)'
lustre: 	'Vitreous or pearly'
ore: 		'None'
fact: 		'Calcite refracts light, making you see two images instead of one'
uses: 		'Fabricating optical sights on weapons for World War II. Construction material, abrasive, agricultural soil treatment, construction aggregate, pigment, pharmaceuticals and more. It has more uses than almost any other mineral'
extractors: 'Stalagmites and stalactites are defining characteristics of limestone caverns which are found worldwide, particularly within tropical regions with the more well known ones recognised in Borneo, Iceland and Mexico. Salt rich bodies of water which dry up known as playa lakes or salt flats such as the World’s largest in Bolivia, are large sources of calcite'
chabit: 	'Varies more than any other mineral, most common being tabular and prismatic with fibrous, granular, stalactic or massive habits also observed'
cstruct: 	'Trigonal'
depenv:		'Hydrothermal veins and vugs, such as here in Weardale as well as caverns and marine organisms'
tparency: 	'Translucent to transparent'
origin:		'Derived from the greek word \‘Chalix\’ meaning lime'
observed: 	'White and brown'
usesplus: 	'None'
streak: 	'White'
cleavage: 	'Perfect rhombohedral'
fracture: 	'Conchoidal fracture but rarely seen due to the perfect cleavage'
gravity: 	'2.7'
properties: 'The phenomenon of double refraction causes a single dot on a piece of paper display 2 dots. If rotated, the true dot is stationary with the other rotating to the rhomb. It’s variable habit indicates the depositional temperature conditions'
relevance: 	'Gangue mineral, and used in spar boxes'
opprop: 	'Uniaxial, very common twinning, with lamellar twinning occurring due to exposure of high pressures'
impurities:	'Red due to iron while purple and blue indicate levels of niobium and brown or black include manganese'
hero:		'calcite.jpeg'
thumb:		'calcite-thumb.jpeg'