name:		'Siderite'
formula:	'FeCO3'
colour: 	'Yellowish to dark brown'
abundance: 	'Widespread - found in sedimentary, igneous and metamorphic rocks'
hardness: 	'3.5/4 (medium)'
lustre: 	'Vitreous to pearly'
ore: 		'One of the iron carbonates (iron ore).'
fact: 		'It is a valuable iron mineral, since it is 48% iron and contains no sulfur or phosphorus.'
uses: 		'Siderites main use is for iron smelting, and it is a local but not a major source of iron.'
extractors: 'Iron is produced widely across the globe.'
chabit: 	'Rhombohedral - Tabular crystals, often curved - botryoidal to massive.'
cstruct: 	'Hexagonal/Trigonal'
depenv:		'Well-formed crystals are usually found in hydrothermal veins. In sedimentary rocks it occurs at shallow burial depths as concretions and in thin beds with shale, clay, and coal seams. Well-formed crystals can also be found in some granitic and syenitic pegmatites.'
tparency: 	'Translucent'
origin:		'It takes its name from the Greek word σίδηρος, sideros, meaning “iron”.'
observed: 	'Brown to dark brown and green.'
usesplus: 	'The smelting of iron from ores began in about 2000 BC in Persia. Iron proved a superior metal to bronze in almost every single way, and it’s use ultimately led to the Industrial Revolution. Siderite’s contribution as an ore for iron has not yet been fully determined.'
streak: 	'White'
cleavage: 	'Perfect, rhombohedral'
fracture: 	'Uneven or Conchoidal'
gravity: 	'3.9'
properties: 'None'
relevance: 	'Economic value and used in spar boxes.'
opprop: 	'Occasional lamellar twinning.'
impurities:	'Color range from yellow to dark brown or black, the latter being due to the presence of manganese.'
hero:		'siderite.jpeg'
thumb:		'siderite-thumb.jpeg'
