name:		 'Smithsonite'
formula:	'ZnCO3'
colour: 	'White, blue, green, yellow, brown, pink, colourless'
abundance: 	'Fairly common mineral found in the oxidation zone of most zinc deposits'
hardness: 	'4 - 4.5 (medium)'
lustre: 	'Vitreous to pearly'
ore: 		'Zinc'
fact: 		'First named \'calamine\', it was renamed when it was discovered both smithsonite and hemimorphite had been grouped under the same name'
uses: 		'Zinc is used for galvanizing steel, producing brass and bronze as well as zinc base alloys'
extractors: 'Significant deposits in Italy, Greece, Namibia, Germany, Mexico, Zambia, US and Australia'
chabit: 	'Botryoidal or rhombohedral'
cstruct: 	'Hexagonal or Scalenohedral'
depenv:		'Smithsonite occurs as a secondary mineral in the weathering or oxidation zone of zinc-bearing ore deposits. It sometimes occurs as replacement bodies in carbonate rocks'
tparency: 	'Translucent to opaque'
origin:		'Named after James Smithson (1765-1829), English mineralogist who financed the founding of the Smithsonian Institution in Washington, DC, USA'
observed: 	'Yellow/green, grey/brown'
usesplus: 	'Smithsonite is occasionally cut as ornaments and \'en cabochon\' as gems'
streak: 	'White'
cleavage: 	'Perfect rhombohedral'
fracture: 	'Uneven to Conchoidal'
gravity: 	'4.4 - 4.5'
properties: 'Part of the carbonate group'
relevance: 	'Zinc ore found in the area'
opprop: 	': Perfect cleavage on [1011], no twinning'
impurities:	'None'
hero:		'smithsonite.jpeg'
thumb:		'smithsonite-thumb.jpeg'
