name:		'Sphalerite'
formula:	'(Zn,Fe)S (Zinc Sulfide)'
colour: 	'Typically red, brown/black or yellow'
abundance: 	'It is found in a multitude of countries Worldwide'
hardness: 	'3.5-4 (soft to medium)'
lustre: 	'Typically resinous while opaque specimens exhibit a shiny sub-metallic lustre'
ore: 		'Zinc'
fact: 		'Copper, silver and tin are often recorded in sphalerite'
uses: 		'Crystals of suitable size and transparency can be fashioned into gemstones'
extractors: 'Sphalerite is produced worldwide, such as the Alston Moor, Germany, Switzerland, Canada and North and South America'
chabit: 	'Tetrahedral or rhombidodecahedron'
cstruct: 	'Cubic'
depenv:		'Like Killhope, many deposits form where hydrothermal activity or contact metamorphism has brought hot, acidic, zinc-bearing fluids in contact with carbonate rocks'
tparency: 	'Pure zinc sphalerites can be colourless and transparent, but iron will decrease translucency and the deepen the colour'
origin:		'It takes its name from the Greek word spaleros meaning slippery/deceitful, as it was easily mistaken for galena'
observed: 	'Black'
usesplus: 	'The amount of iron that be accommodated in the sphalerite structure increases with increasing temperature, therefore it can be used as a geological thermometer. Industrial uses for zinc involve the production of brass and bronze alloys, an anti-corrosive in the galvanising of sheet steel and iron, galvanic elements, pigments such as zinc white, litopone, zinc yellow and in insecticides'
streak: 	'Brown to light yellow or white streak'
cleavage: 	'Perfect rhombohedral'
fracture: 	'Conchoidal'
gravity: 	'3.9 - 4.1'
properties: 'Pure sphalerite transforms to the wurtzite polymorph at 1020°C if oxidation is prevented, but the inversion temperature is lowered by the presence of iron and manganese. Wurtzite can remain stable under 1020°C but any applied stress will convert it into sphalerite'
relevance: 	'Major economic mineral associated with galena'
opprop: 	'Multiple contact twins, penetration twins  and lamellar intergrowths are common'
impurities:	'Green with cobalt and iron, red with tin, indium, silver and molybdenum and yellow often indicating a presence of carbon, copper, mercury, cadmium or germanium'
hero:		'sphalerite.jpeg'
thumb:		'sphalerite-thumb.jpeg'
